export const FAQS_MENU_SHOW = "FAQS_MENU_SHOW";
export const FAQS_REQUEST_WEBSITES = "FAQS_REQUEST_WEBSITES";
export const FAQS_REQUEST_BOOKKEEPING = "FAQS_REQUEST_BOOKKEEPING";
export const FAQS_REQUEST_SUPPORTS = "FAQS_REQUEST_SUPPORTS";
export const FAQS_REQUEST_MEDICINE = "FAQS_REQUEST_MEDICINE";

export const FAQS_REQUEST_STARTED = "FAQS_REQUEST_STARTED";
export const FAQS_REQUEST_FINISHED = "FAQS_REQUEST_FINISHED";
export const FAQS_REQUEST_ERROR = "FAQS_REQUEST_ERROR";
export const FAQS_REQUEST_MAIL_MESSAGES = "FAQS_REQUEST_MAIL_MESSAGES";
export const FAQS_DELETE_SUCCESS = "FAQS_DELETE_SUCCESS";
export const FAQS_SET_EDITABLE_ELEMENT = "FAQS_SET_EDITABLE_ELEMENT";
export const CLEAR_EDITABLE_ELEMENT = "CLEAR_EDITABLE_ELEMENT";
