export const FAQS_MENU_SHOW = "FAQS_MENU_SHOW";

export const FAQS_REQUEST_STARTED = "FAQS_REQUEST_STARTED";
export const FAQS_REQUEST_FINISHED = "FAQS_REQUEST_FINISHED";
export const FAQS_REQUEST_ERROR = "FAQS_REQUEST_ERROR";
export const FAQS_REQUEST_TOPICS = "FAQS_REQUEST_TOPICS";
export const FAQS_REQUEST_REGLAMENTS = "FAQS_REQUEST_REGLAMENTS";
export const FAQS_ORGSTRUCTURE_SUCCESS = "FAQS_ORGSTRUCTURE_SUCCESS";
export const FAQS_REQUEST_COMPANIES = "FAQS_REQUEST_COMPANIES";
export const FAQS_REQUEST_MAIL_MESSAGES = "FAQS_REQUEST_MAIL_MESSAGES";
export const FAQS_REQUEST_DEPARTMENTS = "FAQS_REQUEST_DEPARTMENTS";
export const FAQS_REQUEST_POSITIONS = "FAQS_REQUEST_POSITIONS";
export const FAQS_DELETE_SUCCESS = "FAQS_DELETE_SUCCESS";
export const FAQS_SET_EDITABLE_ELEMENT = "FAQS_SET_EDITABLE_ELEMENT";
export const CLEAR_EDITABLE_ELEMENT = "CLEAR_EDITABLE_ELEMENT";
