stages:
  - off_old_version
  - deploy
off_old_vesrion:
  stage: off_old_version
  script:
    - docker-compose down
deploy:
  stage: deploy
  script:
    - docker-compose up
  only:
    - merge_requests
    - master