image: docker

services:
  - docker:dind
stages:
  - deploy
    # variables:
#   DOCKER_DRIVER: overlay2
#   # Create the certificates inside this directory for both the server
#   # and client. The certificates used by the client will be created in
#   # /certs/client so we only need to share this directory with the
#   # volume mount in config.toml.
#   DOCKER_TLS_CERTDIR: "/certs"

# services:
#   - docker:19.03.0-dind

before_script:
  - apk add --update python py-pip python-dev && pip install docker-compose # install docker-compose
  - docker version
  - docker-compose version
step-deploy-prod:
  stage: deploy
  only:
    - master
    - merge_requests
  script:
    - docker-compose build --no-cache
    - docker-compose up -d

#build_image:
#  script:
#    - docker build .
#    - docker-compose build
#    - docker-compose up -d
