before_script:
  - docker info
  - docker-compose -v

build_image:
  script:
    - docker build -t my-docker-image .
    - docker run my-docker-image /script/to/run/tests
  only:
    - master
    - merge_requests