stages:
  - deploy

before_script:
  - docker info
  - docker-compose -v

build_image:
  stage: deploy
  script:
    - docker-compose build
    - docker-compose up -d
  only:
    - master
    - merge_requests
