version: '3.7'

services:
  backend:
    build:
      ./packages/backend
    restart: always
    network_mode: "host"
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      FRONT_PORT: "${FRONT_PORT}"
      FRONT_HOST: "${HOST}"
      HOST: "${HOST}"
      BACK_PORT: "${BACK_PORT}"
    # ports:
    # - "${BACK_PORT}:${BACK_PORT}"
  frontend:
    build:
      ./packages/frontend
    restart: always
    network_mode: "host"
    environment:
      REACT_APP_BACK_PORT: "${BACK_PORT}"
      REACT_APP_FRONT_PORT: "${FRONT_PORT}"
      REACT_APP_BACK_HOST: "${HOST}"
    # ports:
    # - "${FRONT_PORT}:${FRONT_PORT}"
