version: '3.7'

services:
  backend:
    build:
      ./packages/backend
      networks:
          - default
    restart: always
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      FRONT_PORT: "${FRONT_PORT}"
    ports:
    - "${BACK_PORT}:${BACK_PORT}"
  frontend:
    build:
      ./packages/frontend
    restart: always
    environment:
      REACT_APP_BACK_PORT: "${BACK_PORT}"
      REACT_APP_FRONT_PORT: "${FRONT_PORT}"
      REACT_APP_BACK_HOST: backend
    ports:
    - "${FRONT_PORT}:${FRONT_PORT}"
    depends_on:
      - backend
networks:
  default:
    external:
      name: host