export const GET_APPEALS = 'GET_APPEALS';
export const APPEALS_REQUEST_PENDING = 'APPEALS_REQUEST_PENDING';
export const APPEALS_SUCCESS = 'APPEALS_SUCCESS';
export const APPEALS_ERROR = 'APPEALS_ERROR';