env:
  browser: true
  es2021: true
extends:
  - "eslint:recommended"
  - airbnb
  - "plugin:jsx-a11y/recommended"
  - "plugin:import/errors"
  - "plugin:import/warnings"
  - "plugin:react-hooks/recommended"
  - "plugin:react/recommended"
  - "plugin:prettier/recommended"
  - prettier
  # - prettier/prettier
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - prettier
settings:
  import/ignore:
    - "node": {
      "extensions": [".js", ".jsx", ".ts", ".tsx", ".native.js"]
    }
rules: {
  "prettier/prettier": [2, {
    "singleQuote": false, 
    "trailingComma": "none",
    "tabWidth": 2,
    "parser": "flow", 
    "printWidth": 80,
    "bracketSpacing": true,
    "arrowParens": "always" 
  }],
  "react/jsx-filename-extension": [0, { "extensions": [".js", ".jsx"] }],
  "react/prop-types": 0,
  "react/destructuring-assignment": [1, "always", { "ignoreClassFields": false }],
  "react/jsx-curly-brace-presence":[1,{ "props": "never", "children": "never" }],
  "react/jsx-curly-brace-availability": [0,{ "props": "ignore", "children": "ignore" }],
  "react-hooks/rules-of-hooks": 2,
  "react-hooks/exhaustive-deps": 0,
  "react/react-in-jsx-scope": 0,
  "react/jsx-props-no-spreading": 0,
  "react/jsx-key": 0,
  "react/no-array-index-key": 0,
  "react/display-name": 0,
  "react/jsx-no-bind": 0,
  "react/jsx-boolean-value": [2,"always"],
  "semi": [2, "always"],
  "comma-dangle": [2, "never"],
  "no-console": 0,
  "no-unused-vars": 0,
  "no-plusplus": 0,
  "no-lonely-if": 0,
  "import/prefer-default-export": 0,
  "import/order": 0,
  "import/no-extraneous-dependencies": 0,
  "import/no-unresolved": [0, {commonjs: true, amd: true}],
  "jsx-quotes": [1,"prefer-double"],
  "no-ternary": 0,
  "no-nested-ternary": 0,
  "no-useless-concat": 0,
  "no-spaced-func": 0,
  "no-import-assign": 2,
  "no-duplicate-imports": [2, { "includeExports": true }],
  "no-shadow": 0,
  "object-shorthand": 0,
  "array-bracket-newline": [2, { "multiline": true }],
  "consistent-return": [1, { "treatUndefinedAsUnspecified": false }],
  "arrow-body-style": [1, "always"],
  "arrow-parens": [2, "always"],
  "prefer-arrow-callback": 0,
  "template-curly-spacing": [2, "never"],
  "object-curly-spacing": [2, "always", { "arraysInObjects": true , "objectsInObjects": true }],
  "jsx-a11y/click-events-have-key-events": 0,  
  "jsx-a11y/alt-text": [ 2, {
    "elements": [ "img", "object", "area", "input[type=\"image\"]" ],
    "img": ["Image"],
    "object": ["Object"],
    "area": ["Area"],
    "input[type=\"image\"]": ["InputImage"]
  }],
  'jsx-a11y/no-static-element-interactions': 
    [
      0,
      {
        handlers: [
          'onClick',
          'onMouseDown',
          'onMouseUp',
          'onKeyPress',
          'onKeyDown',
          'onKeyUp',
        ],
      },
    ],
}
