//  для одной заявки
export const APPEAL_REQUEST_STARTED = "APPEAL_REQUEST_STARTED";
export const APPEAL_GET_SUCCESS = "APPEAL_GET_SUCCESS";
export const APPEAL_REQUEST_ERROR = "APPEAL_REQUEST_ERROR";
export const APPEAL_UPDATE_SUCCESS = "APPEAL_UPDATE_SUCCESS";
export const APPEAL_CREATE_SUCCESS = "APPEAL_CREATE_SUCCESS";
//  для всех заявок
export const APPEALS_GET_SUCCESS = "APPEALS_GET_SUCCESS";
export const APPEALS_REQUEST_ERROR = "APPEALS_REQUEST_ERROR";
export const APPEALS_REQUEST_STARTED = "APPEALS_REQUEST_STARTED";
export const APPEALS_FILTER_SUCCESS = "APPEALS_FILTER_SUCCESS";
// для чата заявки
export const APPEAL_GET_CHAT_MESSAGES = "APPEAL_GET_CHAT_MESSAGES";
export const APPEAL_GET_CHAT_MESSAGE = "APPEAL_GET_CHAT_MESSAGE";
export const APPEAL_CREATE_CHAT_MESSAGE = "APPEAL_CREATE_CHAT_MESSAGE";
