export const GET_TICKETS = 'GET_TICKETS';
export const TICKETS_REQUEST_PENDING = 'TICKETS_REQUEST_PENDING';
export const TICKETS_SUCCESS = 'TICKETS_SUCCESS';
export const TICKETS_ERROR = 'TICKETS_ERROR';