export const GET_APPEALS = 'GET_APPEALS';
export const GET_APPEAL = 'GET_APPEAL';
export const APPEALS_REQUEST_PENDING = 'APPEALS_REQUEST_PENDING';
export const APPEALS_SUCCESS = 'APPEALS_SUCCESS';
export const APPEALS_ERROR = 'APPEALS_ERROR';
export const SELECTED_APPEALS = 'SELECTED_APPEALS';