export const SET_APPEALS = "SET_APPEALS";
export const SET_APPEAL = "SET_APPEAL";
export const APPEALS_REQUEST_PENDING = "APPEALS_REQUEST_PENDING";
export const APPEALS_REQUEST_SUCCESS = "APPEALS_REQUEST_SUCCESS";
export const APPEALS_REQUEST_ERROR = "APPEALS_REQUEST_ERROR";
export const SAVE_SELECTED_APPEALS = "SAVE_SELECTED_APPEALS";