export const APPEAL_REQUEST_STARTED = "APPEAL_REQUEST_STARTED";
export const APPEAL_GET_SUCCESS = "APPEAL_GET_SUCCESS";
export const APPEAL_REQUEST_ERROR = "APPEAL_REQUEST_ERROR";
export const APPEAL_UPDATE_SUCCESS = "APPEAL_UPDATE_SUCCESS";
export const APPEAL_CREATE_SUCCESS = "APPEAL_CREATE_SUCCESS";
export const APPEALS_GET_SUCCESS = "APPEALS_GET_SUCCESS"
export const APPEALS_REQUEST_ERROR = "APPEALS_REQUEST_ERROR"
export const APPEALS_REQUEST_STARTED = "APPEALS_REQUEST_STARTED"
