export const AXIOS_USERS_PENDING = "AXIOS_USERS_PENDING"
export const AXIOS_USERS_SUCCESS = "AXIOS_USERS_SUCCESS"
export const AXIOS_USERS_ERROR = "AXIOS_USERS_ERROR"
export const AXIOS_AUTHORIZE_USER_ERROR = "AXIOS_AUTHORIZE_USER_ERROR"
export const AXIOS_AUTHORIZE_USER_PENDING = "AXIOS_AUTHORIZE_USER_PENDING"
export const AXIOS_DELETE_USER_PENDING = "AXIOS_DELETE_USER_PENDING"
export const AXIOS_DELETE_USER_ERROR = "AXIOS_DELETE_USER_ERROR"

